const data = [
    { "id": 1,  "date": 2012,"price": 30, "name": "Black Ops 2", "category": "Shooting", "description": "Call of Duty: Black Ops II is a 2012 first-person shooter video game developed by Treyarch and published by Activision." },
    { "id": 2,  "date": 2009,"price": 19, "name": "Left 4 Dead 2", "category": "Shooting", "description": "Left 4 Dead 2 is a 2009 first-person shooter game developed and published by Valve." },
    { "id": 3,  "date": 2001,"price": 30, "name": "Halo: Combat Evolved", "category": "Shooting", "description": "Halo: Combat Evolved is a 2001 first-person shooter game developed by Bungie and published by Microsoft Game Studios." },
    { "id": 4,  "date": 2004,"price": 30, "name": "Grand Theft Auto: San Andreas", "category": "Shooting", "description": "Grand Theft Auto: San Andreas is a 2004 video game developed by Rockstar North and published by Rockstar Games." },
    { "id": 5,  "date": 1997,"price": 10, "name": "Tekken 3", "category": "Fighting", "description": "Tekken 3 is a fighting game, the third entry in the Tekken series. It was released to the arcades in 1997, before being ported for the PlayStation in 1998." },
    { "id": 6,  "date": 1997,"price": 15, "name": "Street Fighter III", "category": "Fighting", "description": "Street Fighter III: New Generation is a fighting video game in Capcom's Street Fighter series, originally released as a coin-operated arcade game in 1997." },
    { "id": 7,  "date": 2011,"price": 25, "name": "Mortal Kombat komplete edition", "category": "Fighting", "description": "Mortal Kombat is a fighting video game developed by NetherRealm Studios and published by Warner Bros." },
    { "id": 8,  "date": 2004,"price": 30, "name": "Def Jam: Fight For NY", "category": "Fighting", "description": "Def Jam: Fight for NY is a hip hop-influenced action video game published by EA Games. It was released on September 20, 2004." },
    { "id": 9,  "date": 2005,"price": 15, "name": "Midnight Club 3: Dub Edition", "category": "Racing", "description": "Midnight Club 3: Dub Edition is a racing video game developed by Rockstar San Diego and published by Rockstar Games." },
    { "id": 10, "date": 2004, "price": 15, "name": "Need for Speed: Underground 2", "category": "Racing", "description": "Need for Speed: Underground 2 is a 2004 racing video game developed by EA Black Box and published by Electronic Arts." },
    { "id": 11, "date": 2004, "price": 10, "name": "Burnout 3: Takedown", "category": "Racing", "description": "Burnout 3: Takedown is a 2004 racing video game developed by Criterion Games and published by Electronic Arts." },
    { "id": 12, "date": 2014, "price": 30, "name": "Forza Horizon 4", "category": "Racing", "description": "Forza Horizon 2 is a 2014 racing video game developed by Microsoft." },
    { "id": 13, "date": 2005, "price": 10, "name": "The Incredible Hulk: Ultimate Destruction", "category": "Superhero", "description": "The Incredible Hulk: Ultimate Destruction is a 2005 video game developed by Radical Entertainment and published by Vivendi Universal Games." },
    { "id": 14, "date": 2007, "price": 10, "name": "Spider-Man 3", "category": "Superhero", "description": "Spider-Man 3 is a 2007 action-adventure video game based on the Marvel Comics character Spider-Man." },
    { "id": 15, "date": 2011, "price": 15, "name": "Batman: Arkham City", "category": "Superhero", "description": "Batman: Arkham City is a 2011 action game developed by Rocksteady Studios and published by Warner Bros." },
    { "id": 16, "date": 2003, "price": 10, "name": "Enter The Matrix", "category": "Superhero", "description": "Enter the Matrix is a 2003 action video game developed by Shiny Entertainment and published by Infogrames under the Atari brand name." },
    { "id": 17, "date": 2001, "price": 30, "name": "Sonic Adventure 2", "category": "Adventure", "description": "Sonic Adventure 2 is a 2001 platform game developed by Sonic Team USA and published by Sega." },
    { "id": 18, "date": 2014, "price": 30, "name": "Mario Kart 8 Deluxe", "category": "Adventure", "description": "Mario Kart 8 is a kart racing game developed and published by Nintendo." },
    { "id": 19, "date": 2005, "price": 25, "name": "Super Mario Strikers", "category": "Adventure", "description": "Super Mario Strikers, known in Europe and Australia as Mario Smash Football, is a 2005 sports video game developed by Next Level Games and published by Nintendo" },
    { "id": 20, "date": 2003, "price": 10, "name": "The Simpsons: Hit & Run", "category": "Adventure", "description" : "The Simpsons: Hit & Run is a 2003 action-adventure game developed by Radical Entertainment and published by Vivendi Universal Games." },
]

export default data